### ISSUE TITLE
🐛 type error on hosted app

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#157]
It is unclear if this error happens because of data errors or specificially in hosted env.

Logged in with demo@ account on hosted chart app.

![type_error](https://user-images.githubusercontent.com/14337958/59453056-5c8e6400-8e0f-11e9-8779-01ddaa263179.gif)

error:
<img width="348" alt="Screen Shot 2019-06-13 at 21 15 00" src="https://user-images.githubusercontent.com/14337958/59453156-919ab680-8e0f-11e9-9970-fafcd5e73c2a.png">

**Comment by eliascodes** [comment]
It's because `legendData` is shorter than `rows` in the following:
https://github.com/TwinePlatform/twine-monolith/blob/ec2a64dcba62d9d620b15f9e4ea2e5259c7b2f68/dashboard-app/src/components/StackedBarChart/utils/util.ts#L45

Typescript appears to not tell us that accessing the `active` is unsafe. There should be a run-time assertion.

**Comment by astroash** [comment]
Unable to recreate locally. Steps taken:

- check if it is a data/db issue
	- clone twine-api-staging db & restore run locally
	- clone twine-api-staging-qa db & restore run locally
- run built version of the app locally
