### ISSUE TITLE
Extract volunteer projects model methods

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#296]
Either ahead of or as part of upcoming work on volunteer projects, extract volunteer log project methods out of the `VolunteerLogs` model and into its own `VolunteerProjects` model.

In addition add a new constraint on the table to replace the existence/uniqueness checks e.g.:
```sql
ALTER TABLE volunteer_project ADD CONSTRAINT volunteer_project_constraint_unique_name UNIQUE (organisation_id, volunteer_project_name);
```
Then instead of doing `SELECT EXISTS...` checks we can instead catch unique constraint violations.

**Comment by astroash** [comment]
We can't add this constraint until we have a way to see soft deleted & undelete projects, otherwise the following will happen:

1. Admin creates a project
2. Admin deletes project
3. Admin realises that the project hasn't ended and they need to continue adding to the project
4. Admin cannot find any record of the project so tries to recreate it
5. A user error is displayed that says this project already exists, which is contradictory to the UI they are presented with

**Comment by eliascodes** [comment]
Yep, good point

**Comment by eliascodes** [comment]
superseded by #328
