### ISSUE TITLE
Remaining UX comments from #362

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#404]
These can be taken back to the team:

1. Should legend state be persisted when switching back and forth between projects and activities?
2. When toggled to "projects" the table displays only two projects in rows, but when flipped to "activities" the table displays six projects in columns. These should be consistent.
   - although, looking at it again, this behaviour is consistent with the "volunteers" view -- volunteers with zero hours don't appear in the list. Maybe we should probably leave this for now.
3. UX concerns about the projects/activities toggle [see here and following conversation](https://github.com/TwinePlatform/twine-monolith/pull/362#issuecomment-552932406)
4. Double check whether datepickers on each page are actually appropriate settings (i.e. month or day)
5. Double check the time span limit on projects datepicker

**Comment by astroash** [comment]
It's also worth finding out if we want to display some text if a community business hasn't started using Projects yet, as the graphs look a little weird in this case:

<img width="1083" alt="Screen Shot 2019-11-15 at 16 34 37" src="https://user-images.githubusercontent.com/14337958/68959414-e0d18280-07c5-11ea-992e-9c58a4b96b3c.png">
<img width="1072" alt="Screen Shot 2019-11-15 at 16 34 49" src="https://user-images.githubusercontent.com/14337958/68959418-e5963680-07c5-11ea-9633-3610c4d8c8da.png">

This could be something along the lines of:

'You currently only have one Project. Too track volunteer time under different projects add a new Project on the volunteer app.'

**Comment by astroash** [comment]
Sidenote: If there's time, some bottom padding to the charts would also be great
<img width="822" alt="Screen Shot 2019-11-15 at 16 37 34" src="https://user-images.githubusercontent.com/14337958/68959797-b633f980-07c6-11ea-9c56-3c65fe042545.png">

**Comment by edwardwptc** [comment]
I like this so far, it confused me at first but after looking at it and pressing the buttons for maybe 2mins it became completely obvious what I was doing, looking at and able to access. 

1. No. It suggests persistence across the swap, to me. If you deselect "General" and leave "Heads and Tails" enabled, then swap to activities, and then back, its clear your selection has been wiped by the swap. If when I returned it still showed General deselected, I would presume that the data in between (after I click activities but before I swap back) is somehow filtered because the selection persists, which is not true (and not relevant because it doesn't work that way). 
2. I haven't understood this but I can't find anything wrong with it. 
3. I understood what I was doing very quickly; this might not be the case for others, of course, but I think the combination of set Activities which are recognisable to anyone who knows the app, and the set list of Projects that they authored, it won't take them long to understand what is being presented. 
4. I'm not sure about Day or Month, to be honest with you. I have other concerns about date, see below.
5. People will need "all time" data - 100% if this is how we are presenting it to people. If I have a project that runs for 3 years, having to pull 12 months data, storing it, pulling the next 12 months, storing that and then adding them all together etc is not effective. See below also.

My first impression of this is that it's a great way of displaying complex info and I'm consistently staggered about how excellent both of you are :D 

Forgive me then for adding this, and I understand this may have not been present in the user story at all, so it's not "missing" but something to consider: 

As a Project Co-ordinator or Volunteer Co-ordinator, how do I know who is giving time to a particular project? They might want a list of volunteers. This might end up being displayed elsewhere for simplicity. 

Is there a way for this to show me total data per month without me having to add it all up? If I want to see if a Project's volunteering time is decreasing or increasing I'd have to filter the time, save in memory what the totals are, and then change the filter and compare the new result, or export and graph it myself. Could we reproduce the "by time" chart, with Projects instead of Activities, here? I know that is by month. This feeds in to point 4 above, because if we simply say "Jan 2018 to Jan 2019" monthly breakdowns are easy.

**Comment by eliascodes** [comment]
1. Persist legend state but don't link them
2. Park for now (user testing needed)
3. Park for now (user testing needed)
4. Multiple options to consider -- time chart on projects page, projects toggle on time page
5. See above.
6. Prompting would be more useful on the volunteer app

Additional:
- Colours must be either consistent in meaning or different between projects/activities
