### ISSUE TITLE
expand gender options

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#409]
list to be provided by @edwardwptc

**Comment by edwardwptc** [comment]
Let's go with:
Male
Female
Non-binary
Intersex
Other
Prefer not to say

Don't read this if you're not interested but here's our rationale: 
Intersex people, those with not clearly male or female primary sex characteristics at birth, are a statistically significant portion of the population at birth (between 1.5 to 5%). This can be due to genetic disorders, chromosomal disorders, or pure physical 'abnormalities'. Statistics are uncertain because Western society doesn't recognise this as "normal" and parents/doctors tend to make decisions about the child's sex one way or the other. As such, the adult population who are intersex is much lower. Many may be living without ever knowing they were intersex at birth. 

The general thinking is that "Intersex" is a category of "Sex". Male, Female, Intersex, in terms of biology.  There's a growing movement which suggests Intersex is an appropriate gender category too - people can identify as intersex. It's different to all the other categories, so we'll list it :)

**Comment by astroash** [comment]
> Don't read this if you're not interested but here's our rationale:

Gender diversity is something that interests me. I've not come across intersex described as a gender before but totally get that people may choose this term to identify with.

On defaults, I assume:
- we will be adding these extra options
- gender will still be optional
- if not selected will default to 'prefer not to say'

**Comment by edwardwptc** [comment]
Assumptions are perfect. 

Further reading about the intersex as a gender thing if you're interested:
https://www.intersexequality.com/how-intersex-people-identify/

**Comment by astroash** [comment]
That was an interesting read. Thank you for sharing 🙂
