### ISSUE TITLE
✨ server changes to support volunteer dashboard

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#8]
### User Story 003

**Endpoint**
- ` GET/community-business/me/volunteer-logs` *already supported*

**Endpoint filter/query:**
- sort by & order asc/dec
- dates between

**Client side Manipulation:**
- group logs by activity per user
- total logs per user

### User Story 006

Not currently supported.
**Endpoint**
same as above

**Endpoint filter/query:**
same as above

**Client side Manipulation:**
- group logs by month per user
- total logs per user

### User Story 007
Not currently supported.
**Endpoint:**
- `/community-business/me/volunteer-logs

**Endpoint filter/query:**
same as above

**Client side Manipulation:**
- group logs by activity per month
- total logs per activity

**Comment by eliascodes** [comment]
What do we mean by "not currently supported"? Looks like we only need `GET /community-businesses/me/volunteer-logs?since=DATE&until=DATE`, given the return types include the activity and user ids and names (though I'm thoughts about whether this is actually a good idea, but I won't go into that here).

**Comment by astroash** [comment]
My bad, that was an oversight by me! I'll edit the above

**Comment by astroash** [comment]
No changes needed ✨
